// Generated by gencs from interactive_customer_service/Conversation.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace interactive_customer_service 
	{
		[System.Serializable]
		public class Conversation : RosMessage
		{
			public string type;
			public string detail;


			public Conversation()
			{
				this.type = "";
				this.detail = "";
			}

			public Conversation(string type, string detail)
			{
				this.type = type;
				this.detail = detail;
			}

			new public static string GetMessageType()
			{
				return "interactive_customer_service/Conversation";
			}

			new public static string GetMD5Hash()
			{
				return "bba604969c74829213ce33cc79f846d0";
			}
		} // class Conversation
	} // namespace interactive_customer_service
} // namespace SIGVerse.RosBridge

