// Generated by gencs from interactive_customer_service/RobotStatus.msg
// DO NOT EDIT THIS FILE BY HAND!

using System;
using System.Collections;
using System.Collections.Generic;
using SIGVerse.RosBridge;
using UnityEngine;


namespace SIGVerse.RosBridge 
{
	namespace interactive_customer_service 
	{
		[System.Serializable]
		public class RobotStatus : RosMessage
		{
			public string state;
			public bool speaking;
			public string grasped_item;


			public RobotStatus()
			{
				this.state = "";
				this.speaking = false;
				this.grasped_item = "";
			}

			public RobotStatus(string state, bool speaking, string grasped_item)
			{
				this.state = state;
				this.speaking = speaking;
				this.grasped_item = grasped_item;
			}

			new public static string GetMessageType()
			{
				return "interactive_customer_service/RobotStatus";
			}

			new public static string GetMD5Hash()
			{
				return "32361534820efc18b64395ecf70c09b9";
			}
		} // class RobotStatus
	} // namespace interactive_customer_service
} // namespace SIGVerse.RosBridge
